//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD_DiplomadoUASD_Empleados_Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EMPLEADO
    {
        public int Id_Empleado { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int Id_Puesto { get; set; }
        public int Id_Departamento { get; set; }
        public double Salario { get; set; }
    
        public virtual TBL_DEPARTAMENTO TBL_DEPARTAMENTO { get; set; }
        public virtual TBL_PUESTO TBL_PUESTO { get; set; }
    }
}
