//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD_DiplomadoUASD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PELICULA
    {
        public int Codigo { get; set; }
        public string Titulo { get; set; }
        public string Director { get; set; }
        public string AutorPrincipal { get; set; }
        public Nullable<int> No_Actores { get; set; }
        public Nullable<double> Duracion { get; set; }
        public Nullable<int> Estreno { get; set; }
    }
}
